name: Deploy Vite para GitHub Pages

on:
  push:
    branches: ["main"] # Se sua branch for 'master', troque aqui!

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        # AQUI VOCÊ INJETA SUA VARIÁVEL (troque NOME_DA_VARIAVEL pelo que você criou)
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }} 
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
